### ISSUE TITLE
i18n isn't a legal global attribute

### ISSUE THREAD

**Issue by Myhlamaeus** [FelschR/light-i18n#16]
The current [WHATWG Living Standard](https://html.spec.whatwg.org/multipage/dom.html#global-attributes) doesn't list i18n as global attribute. It should probably be replaced with data-i18n.

**Comment by Myhlamaeus** [comment]
@FelschR is there any reason to prefer i18n over data-i18n, seeing as how it is non-standard?

**Comment by felschr** [comment]
It's shorter. But yes, data-i18n would probably be more correct.
